project:
  type: website

website:
  title: "My Very First Portolio Edition"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Projects/
        text: Projects
    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



